#include "Models/PBRMaterialTypes.h"

const FName FPBRChannels::BaseColor(TEXT("BaseColor"));
const FName FPBRChannels::Normal(TEXT("Normal"));
const FName FPBRChannels::NormalDX(TEXT("NormalDX"));
const FName FPBRChannels::NormalGL(TEXT("NormalGL"));
const FName FPBRChannels::Roughness(TEXT("Roughness"));
const FName FPBRChannels::Glossiness(TEXT("Glossiness"));
const FName FPBRChannels::Metallic(TEXT("Metallic"));
const FName FPBRChannels::Specular(TEXT("Specular"));
const FName FPBRChannels::AO(TEXT("AO"));
const FName FPBRChannels::Opacity(TEXT("Opacity"));
const FName FPBRChannels::Height(TEXT("Height"));
const FName FPBRChannels::Displacement(TEXT("Displacement"));
const FName FPBRChannels::Emissive(TEXT("Emissive"));
const FName FPBRChannels::ORM(TEXT("ORM"));
const FName FPBRChannels::ARM(TEXT("ARM"));
const FName FPBRChannels::ClearCoat(TEXT("ClearCoat"));
const FName FPBRChannels::ClearCoatRoughness(TEXT("ClearCoatRoughness"));
const FName FPBRChannels::Anisotropy(TEXT("Anisotropy"));
const FName FPBRChannels::Thickness(TEXT("Thickness"));

const FName FPBRMaterialParameters::BaseColorTexture(TEXT("基础色贴图"));
const FName FPBRMaterialParameters::UseBaseColorTexture(TEXT("使用基础色贴图"));
const FName FPBRMaterialParameters::BaseColorTint(TEXT("基础色调"));
const FName FPBRMaterialParameters::BaseColorIntensity(TEXT("基础色强度"));
const FName FPBRMaterialParameters::NormalTexture(TEXT("法线贴图"));
const FName FPBRMaterialParameters::UseNormalTexture(TEXT("使用法线贴图"));
const FName FPBRMaterialParameters::NormalStrength(TEXT("法线强度"));
const FName FPBRMaterialParameters::RoughnessTexture(TEXT("粗糙度贴图"));
const FName FPBRMaterialParameters::UseRoughnessTexture(TEXT("使用粗糙度贴图"));
const FName FPBRMaterialParameters::RoughnessValue(TEXT("粗糙度数值"));
const FName FPBRMaterialParameters::RoughnessMultiplier(TEXT("粗糙度强度"));
const FName FPBRMaterialParameters::MetallicTexture(TEXT("金属度贴图"));
const FName FPBRMaterialParameters::UseMetallicTexture(TEXT("使用金属度贴图"));
const FName FPBRMaterialParameters::MetallicValue(TEXT("金属度数值"));
const FName FPBRMaterialParameters::MetallicMultiplier(TEXT("金属度强度"));
const FName FPBRMaterialParameters::AOTexture(TEXT("环境遮蔽贴图"));
const FName FPBRMaterialParameters::UseAOTexture(TEXT("使用环境遮蔽贴图"));
const FName FPBRMaterialParameters::AOValue(TEXT("环境遮蔽数值"));
const FName FPBRMaterialParameters::AOMultiplier(TEXT("环境遮蔽强度"));
const FName FPBRMaterialParameters::OpacityTexture(TEXT("透明贴图"));
const FName FPBRMaterialParameters::UseOpacityTexture(TEXT("使用透明贴图"));
const FName FPBRMaterialParameters::Opacity(TEXT("透明度"));
const FName FPBRMaterialParameters::EmissiveTexture(TEXT("自发光贴图"));
const FName FPBRMaterialParameters::UseEmissiveTexture(TEXT("使用自发光贴图"));
const FName FPBRMaterialParameters::EmissiveColor(TEXT("自发光颜色"));
const FName FPBRMaterialParameters::EmissiveIntensity(TEXT("自发光强度"));
const FName FPBRMaterialParameters::SpecularTexture(TEXT("高光贴图"));
const FName FPBRMaterialParameters::UseSpecularTexture(TEXT("使用高光贴图"));
const FName FPBRMaterialParameters::SpecularLevel(TEXT("高光强度"));
const FName FPBRMaterialParameters::HeightTexture(TEXT("高度贴图"));
const FName FPBRMaterialParameters::UseHeightTexture(TEXT("使用高度贴图"));
const FName FPBRMaterialParameters::HeightStrength(TEXT("置换强度"));
const FName FPBRMaterialParameters::PixelDepthOffsetStrength(TEXT("深度偏移强度"));
const FName FPBRMaterialParameters::ClearCoat(TEXT("清漆强度"));
const FName FPBRMaterialParameters::ClearCoatRoughness(TEXT("清漆粗糙度"));
const FName FPBRMaterialParameters::ClearCoatTexture(TEXT("清漆贴图"));
const FName FPBRMaterialParameters::UseClearCoatTexture(TEXT("使用清漆贴图"));
const FName FPBRMaterialParameters::ClearCoatRoughnessTexture(TEXT("清漆粗糙度贴图"));
const FName FPBRMaterialParameters::UseClearCoatRoughnessTexture(TEXT("使用清漆粗糙度贴图"));
const FName FPBRMaterialParameters::Anisotropy(TEXT("各向异性"));
const FName FPBRMaterialParameters::FabricFuzzColor(TEXT("织物绒毛颜色"));
const FName FPBRMaterialParameters::FabricFuzzStrength(TEXT("织物绒毛强度"));
const FName FPBRMaterialParameters::RefractionAmount(TEXT("折射强度"));
const FName FPBRMaterialParameters::WaterColor(TEXT("水体颜色"));
const FName FPBRMaterialParameters::WaterFlowSpeedU(TEXT("水流 U 速度"));
const FName FPBRMaterialParameters::WaterFlowSpeedV(TEXT("水流 V 速度"));
const FName FPBRMaterialParameters::WaterRippleScale(TEXT("水波缩放"));
const FName FPBRMaterialParameters::WaterRippleStrength(TEXT("水波强度"));
const FName FPBRMaterialParameters::UVTiling(TEXT("UV 平铺"));
const FName FPBRMaterialParameters::UVOffset(TEXT("UV 偏移"));
const FName FPBRMaterialParameters::UVUTiling(TEXT("U 平铺"));
const FName FPBRMaterialParameters::UVVTiling(TEXT("V 平铺"));
const FName FPBRMaterialParameters::UVUOffset(TEXT("U 偏移"));
const FName FPBRMaterialParameters::UVVOffset(TEXT("V 偏移"));
const FName FPBRMaterialParameters::UVRotationDegrees(TEXT("UV 旋转角度"));
